### ISSUE TITLE
crash - app crashes when launching intestitial or reward ad

### ISSUE THREAD

**Issue by Epic-Apps-Hub** [vegidio/flutter-appodeal#43]
Sometimes i get this error, sometimes the ad runs regularly
any help?

```E/AndroidRuntime(22733): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.wool.app/com.explorestack.iab.vast.activity.VastActivity}: java.lang.RuntimeException: java.lang.NoSuchMethodException: com.explorestack.iab.vast.i.values []
E/AndroidRuntime(22733):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
E/AndroidRuntime(22733):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
E/AndroidRuntime(22733):        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/AndroidRuntime(22733):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(22733):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(22733):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime(22733):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(22733):        at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(22733):        at android.app.ActivityThread.main(ActivityThread.java:7660)
E/AndroidRuntime(22733):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22733):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(22733):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(22733): Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: com.explorestack.iab.vast.i.values []
E/AndroidRuntime(22733):        at java.lang.Enum.enumValues(Enum.java:270)
E/AndroidRuntime(22733):        at java.lang.Enum.access$000(Enum.java:61)
E/AndroidRuntime(22733):        at java.lang.Enum$1.create(Enum.java:277)
E/AndroidRuntime(22733):        at java.lang.Enum$1.create(Enum.java:275)
E/AndroidRuntime(22733):        at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
E/AndroidRuntime(22733):        at java.lang.Enum.getSharedConstants(Enum.java:289)
E/AndroidRuntime(22733):        at java.lang.Enum.valueOf(Enum.java:243)
E/AndroidRuntime(22733):        at java.io.ObjectInputStream.readEnum(ObjectInputStream.java:1841)
E/AndroidRuntime(22733):        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1409)
E/AndroidRuntime(22733):        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:427)
E/AndroidRuntime(22733):        at android.os.Parcel.readSerializable(Parcel.java:3455)
E/AndroidRuntime(22733):        at android.os.Parcel.readSerializable(Parcel.java:3425)
E/AndroidRuntime(22733):        at com.explorestack.iab.vast.VastRequest.<init>(Unknown Source:67)
E/AndroidRuntime(22733):        at com.explorestack.iab.vast.VastRequest$e.createFromParcel(Unknown Source:2)
E/AndroidRuntime(22733):        at android.os.Parcel.readParcelable(Parcel.java:3281)
E/AndroidRuntime(22733):        at android.os.Parcel.readValue(Parcel.java:3174)
E/AndroidRuntime(22733):        at android.os.Parcel.readArrayMapInternal(Parcel.java:3567)
E/AndroidRuntime(22733):        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
E/AndroidRuntime(22733):        at android.os.BaseBundle.unparcel(BaseBundle.java:236)
E/AndroidRuntime(22733):        at android.os.Bundle.getBundle(Bundle.java:974)
E/AndroidRuntime(22733):        at com.google.firebase.messaging.p.onActivityCreated(com.google.firebase:firebase-messaging@@22.0.0:4)
E/AndroidRuntime(22733):        at android.app.Application.dispatchActivityCreated(Application.java:373)
E/AndroidRuntime(22733):        at android.app.Activity.dispatchActivityCreated(Activity.java:1316)
E/AndroidRuntime(22733):        at android.app.Activity.onCreate(Activity.java:1589)
E/AndroidRuntime(22733):        at com.explorestack.iab.vast.activity.VastActivity.onCreate(Unknown Source:18)
E/AndroidRuntime(22733):        at android.app.Activity.performCreate(Activity.java:8000)
E/AndroidRuntime(22733):        at android.app.Activity.performCreate(Activity.java:7984)
E/AndroidRuntime(22733):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
E/AndroidRuntime(22733):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
E/AndroidRuntime(22733):        ... 11 more
E/AndroidRuntime(22733): Caused by: java.lang.NoSuchMethodException: com.explorestack.iab.vast.i.values []
E/AndroidRuntime(22733):        at java.lang.Class.getMethod(Class.java:2072)
E/AndroidRuntime(22733):        at java.lang.Class.getDeclaredMethod(Class.java:2050)
E/AndroidRuntime(22733):        at java.lang.Enum.enumValues(Enum.java:267)
E/AndroidRuntime(22733):        ... 39 more
```

**Comment by WP517i** [comment]
Similar issue, but only after publication to Google Play!
PLEASE HELP!!!!

java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3308)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3457)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:83)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2044)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:224)
  at android.app.ActivityThread.main (ActivityThread.java:7562)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:539)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:950)
Caused by: java.lang.RuntimeException: 
  at java.lang.Enum.enumValues (Enum.java:270)
  at java.lang.Enum.access$000 (Enum.java:61)
  at java.lang.Enum$1.create (Enum.java:277)
  at java.lang.Enum$1.create (Enum.java:275)
  at libcore.util.BasicLruCache.get (BasicLruCache.java:63)
  at java.lang.Enum.getSharedConstants (Enum.java:289)
  at java.lang.Enum.valueOf (Enum.java:243)
  at java.io.ObjectInputStream.readEnum (ObjectInputStream.java:1841)
  at java.io.ObjectInputStream.readObject0 (ObjectInputStream.java:1409)
  at java.io.ObjectInputStream.readObject (ObjectInputStream.java:427)
  at android.os.Parcel.readSerializable (Parcel.java:3142)
  at android.os.Parcel.readSerializable (Parcel.java:3112)
  at com.explorestack.iab.vast.VastRequest.<init> (VastRequest.java:67)
  at com.explorestack.iab.vast.VastRequest$6.createFromParcel (VastRequest.java:2)
  at android.os.Parcel.readParcelable (Parcel.java:2976)
  at android.os.Parcel.readValue (Parcel.java:2869)
  at android.os.Parcel.readArrayMapInternal (Parcel.java:3252)
  at android.os.BaseBundle.initializeFromParcelLocked (BaseBundle.java:292)
  at android.os.BaseBundle.unparcel (BaseBundle.java:236)
  at android.os.Bundle.getParcelable (Bundle.java:951)
  at android.content.Intent.getParcelableExtra (Intent.java:7953)
  at com.explorestack.iab.vast.activity.VastActivity.onCreate (VastActivity.java:27)
  at android.app.Activity.performCreate (Activity.java:7893)
  at android.app.Activity.performCreate (Activity.java:7880)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1307)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3283)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3457)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:83)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2044)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:224)
  at android.app.ActivityThread.main (ActivityThread.java:7562)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:539)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:950)
Caused by: java.lang.NoSuchMethodException: 
  at java.lang.Class.getMethod (Class.java:2072)
  at java.lang.Class.getDeclaredMethod (Class.java:2050)
  at java.lang.Enum.enumValues (Enum.java:267)
  at java.lang.Enum.access$000 (Enum.java:61)
  at java.lang.Enum$1.create (Enum.java:277)
  at java.lang.Enum$1.create (Enum.java:275)
  at libcore.util.BasicLruCache.get (BasicLruCache.java:63)
  at java.lang.Enum.getSharedConstants (Enum.java:289)
  at java.lang.Enum.valueOf (Enum.java:243)
  at java.io.ObjectInputStream.readEnum (ObjectInputStream.java:1841)
  at java.io.ObjectInputStream.readObject0 (ObjectInputStream.java:1409)
  at java.io.ObjectInputStream.readObject (ObjectInputStream.java:427)
  at android.os.Parcel.readSerializable (Parcel.java:3142)
  at android.os.Parcel.readSerializable (Parcel.java:3112)
  at com.explorestack.iab.vast.VastRequest.<init> (VastRequest.java:67)
  at com.explorestack.iab.vast.VastRequest$6.createFromParcel (VastRequest.java:2)
  at android.os.Parcel.readParcelable (Parcel.java:2976)
  at android.os.Parcel.readValue (Parcel.java:2869)
  at android.os.Parcel.readArrayMapInternal (Parcel.java:3252)
  at android.os.BaseBundle.initializeFromParcelLocked (BaseBundle.java:292)
  at android.os.BaseBundle.unparcel (BaseBundle.java:236)
  at android.os.Bundle.getParcelable (Bundle.java:951)
  at android.content.Intent.getParcelableExtra (Intent.java:7953)
  at com.explorestack.iab.vast.activity.VastActivity.onCreate (VastActivity.java:27)
  at android.app.Activity.performCreate (Activity.java:7893)
  at android.app.Activity.performCreate (Activity.java:7880)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1307)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3283)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3457)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:83)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2044)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:224)
  at android.app.ActivityThread.main (ActivityThread.java:7562)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:539)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:950)

**Comment by WP517i** [comment]
After learning the problem! I found out that the problem is related to the BidMachine AD network
